### ISSUE TITLE
Keefox should not ask you to save a password when you just used a password

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#118]
Many times, after I've used a saved entry, keefox will still ask whether or not I want to save the password.  

I would think that if it autofilled in the box or you used the pull-down for multiple matched entries, it shouldn't ask if you wanted to save it.

**Comment by keystoneclimber** [comment]
Gotta love developers.  Bug report closed, yet I still have the exact same issue running KeeFox 1.4.6.  Your software basically says, here let me fill in all login credentials for this site for you.  By the way, would you like me to save these login credentials (the ones that I already have saved for you) so that you can use them in the future?  Pretty tough to understand, I know.  By the way, "the never for this site" button mysteriously does not work for 192.168.0.1

**Comment by luckyrat** [comment]
If you have problems with the latest version (1.5.3) please open a new issue and describe the problem. This particular issue is not valid but that doesn't mean a clear explanation of a problem in a new issue would be treated the same (as you would see if you looked at the thousands of enhancements and bug fixes I've done for free over the past 8 years).
