### ISSUE TITLE
Allow an easy copy-paste of username/password for forms not recognize

### ISSUE THREAD

**Issue by jbriens** [luckyrat/KeeFox#198]
Hi,
This is an enhancement request. I hope this is the right place to create them. Let me know if not.

As it is very hard to to have Keefox being able to detect all forms, a possible workaround for websites that aren't working is to have a simple user/password copy-paste feature.

Currently for websites that aren't working I am using the following logic:
 1. I right click on the Keepass entry found by Keepass and I select the "edit entry" function.
 1. Then I select the user and I paste it on the form
 1. Then I select the password and I paste it in the appropriate field.
 1. Then I close the edit popup by clicking on cancel

It works, but this is quite cumbersome and it could be advantageously replaced by a new function in the contextual menu of Firefox like "paste username" and "paste password" at least for the record found by default (I guess if several record are found, a sub-menu should be available to select the proper one):
![firefox contextual menu](https://f.cloud.github.com/assets/1647650/1117084/b7b53238-1a47-11e3-884e-e6042e649ac5.jpg)

Alternatively, if this is not easy to implement in the Firefox menu, the same function could be put in the context menu of the Keefox entries:
![keefox contextual menu](https://f.cloud.github.com/assets/1647650/1117085/b7b77854-1a47-11e3-9673-f1617f9a7b1b.jpg)

I hope my explanation are clear enough.

Regards, JM

**Comment by luckyrat** [comment]
This is implemented as new options on the context menu that is available on each login entry in the main KeeFox panel (search results, matched logins and list of all logins). Much of the same code could be re-used in order to add similar functionality to the on-page context menu but I won't consider that feature until after KeeFox 1.5 has been released and we can assess how important an extra access point is compared to other issues. Any such extensions to this feature will need to be created as a new issue.

**Comment by jbriens** [comment]
Hi Luckyrat. Thanks.
