### ISSUE TITLE
KeeFox does not work

### ISSUE THREAD

**Issue by opd** [luckyrat/KeeFox#253]
After today's update keepass not working.
Xubuntu 13.04, KeePass 2.24, Firefox 27.0.1

**Comment by g1ps** [comment]
In case anyone else has the same issue as me, I'm reporting what I found here. My problem was that I'd changed the names of some groups in Keepass, including Keepass's home group. After trying a number of times over a period of several months, I finally stumbled across a reference to this and reassiged the start-up group. Normal functionality was restored immediately. I knew that Keefox was connecting because I could log in and other factors worked, it was just not staying logged in or matching log-ins. The details of how to correct this situation are here:

https://github.com/luckyrat/KeeFox/wiki/en-|-Using-KeeFox

under "Home group".

Phew.

**Comment by jiawanyovan** [comment]
Hi I having problem in my Keefox integration with KeePass. Please review my post in askUbuntu as attached:
http://askubuntu.com/questions/887790/keepass2-portable-authentication-sent-requests-to-firefox-keefox-after-closing

Thank you.

**Comment by jiawanyovan** [comment]
@g1ps Thanks for your answer above, it seems to pacify the error from KeeFox for now. 

@everyone, the suggestion suggested by @g1ps that is proposed originally by the developer @luckyrat seems to be the solution.

**Comment by g1ps** [comment]
:thumbsup:
