### ISSUE TITLE
KeeFox menu button disappeared.

### ISSUE THREAD

**Issue by tea2code** [luckyrat/KeeFox#289]
Hi,

with the new version the menu button disappeared completely. It was previously beside the addressbar but wasn't there anymore after updating to 1.4.2. Checking the customize menu it wasn't there either. I've already tried reinstalling KeeFox and disabling addons like Classic Theme Restorer but for no avail. Other than that KeeFox works perfectly. Passwords are inserted and the toolbar is shown if KeePass isn't open yet. 

Thanks for your work :+1:

**Comment by e-motiv** [comment]
No, I don't think you are being dismissive.  I'm grateful any way.  It was
just in case you'd have an insight or something.
I'll live with the workaround for now, until more people report it or they
could find some time for reinstall and reset and such.

Tanke care!

   [image: Ruby Contact Card]
<http://www.e-motiv.net/Ruben%20Goethals%20-%20e-motiv.vcf>Ruben
<Ruben@e-motiv.net>    @   e-motiv <http://www.e-motiv.net>
 [image: Ruby] <http://www.e-motiv.net>

**Comment by luckyrat** [comment]
For anyone who finds their disappearing button is ending up on the "more menu items" overflow hamburger button, there are some more suggestions in #349

**Comment by konus1** [comment]
I had also the problem with the disappearing keefox button on both, my work and on my home pc. I think it is a bug in interaction with some other addons, I have installed. I already deleted "Evernote Web Clipper" but it was not the (only) solution. Unfortunately debugging is quite difficult, since it seems like it disappears randomly. I ended up moving the icon from addon area up to the tab bar and stopped debugging. sorry.
