### ISSUE TITLE
Not connections to keepass

### ISSUE THREAD

**Issue by rodolfo3** [luckyrat/KeeFox#305]
Keepass is opened and the plugin is installed and running (I can connect into 127.0.0.1:12547 - same port as configured on KeeFox).

My log file have a lot of messages like:
```
Sat Jul 12 2014 15:53:27 GMT-0300 (BRT):WARN:  An attempt to setup the KPRPC secure channel has failed. It will not be retried for at least 10 seconds. If you see this message regularly and are not sure why, please ask on the help forum. Technical detail about the problem follows: [Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: resource://kfmod/kprpcClient.js :: this.getNSILMpassword :: line 748"  data: no]
```
SO.: Debian Linux
Keepass: v2.26
Keepass RPC plugin: v2.0.15.18288
Keefox: v1.4.2
Firefox: 32.0a2

**Comment by luckyrat** [comment]
https://zohodiscussions.com/keefox/topic/you-are-not-logged-in-to-your-password-database-and-cannot-auto-fill-on-ff33#71684000000656018 indicates a possible cause of this problem is a faulty cert8.db file within your Firefox profile. A Firefox reset should fix that problem too.

I'm closing this now because I don't think it is very likely that this problem is specific to KeeFox.
