### ISSUE TITLE
omit QueryString from URL in keepass

### ISSUE THREAD

**Issue by dfherr** [luckyrat/KeeFox#324]
Would it be possible to add an option that automatically omits the query string from the URL when saving new entries to keepas with the keefox plugin?

Would be really appreciated.

**Comment by luckyrat** [comment]
I think that we are all agreed that finding a simple solution for non-technical users is the main goal but we clearly have a few different ideas about how that can be done. In my opinion, one of the simplest solutions for users is the ability to have a "one-click" login button that "just works" for any one of the websites they want to log into. That's what KeeFox (at least most of the time) is able to offer today.

I also agree with the principle that the user should only be shown the details of the URL they are visiting when it is necessary. Although I might disagree with some in that I think it is important for users to know what URL they will go to before they click on it (just knowing it's bbc.co.uk is a simplification too far in some situations).

Unfortunately, the practicalities of enabling one-click logins mean that we have to store the entire URL in the standard KeePass URL field. While storing a separate (and hidden) "one click login" URL in the KeeFox configuration for a KeePass entry would solve this issue, that was not an option when KeeFox was first released so many users have over 5 years worth of stored logins and muscle memory which tells them that the URL they see in KeePass is the URL they will visit when issuing a one-click login. I don't think any amount of notifications, warnings or automated data migration can address this in a way that does not upset at least as many people as it pleases. Even if we were to enable such a feature, the risk of the visible URL and hidden "one-click" URL getting out of sync makes for a complication for the user at best and a complete breakdown of KeeFox functionality at worst.

I think that editing the appearance (but not the stored data) of fields within KeePass is beyond the scope of KeeFox although perhaps a separate KeePass plugin to display a cleaner interface would be worth considering. Frankly, I don't think the display of URL query strings is top of the list of KeePass interface improvements if we're looking to make it accessible to non-technical users.

So I am going to say that this feature request won't be implemented. I'm sorry if that upsets some of you but I hope the explanation above demonstrates that closing this issue is in the best interests of the majority of KeeFox users.
