### ISSUE TITLE
Form recognition improvements

### ISSUE THREAD

**Issue by brainfoolong** [luckyrat/KeeFox#333]
Hi,

just want to point out that the form recognition as a little bit buggy.
For example i really don't not auto fill password for forms with more than 5-6 fields because i'm obiously not in a login form.
I really would like to see some extended tweak params for the form recognition to modify it to fit my needs. At the current state i often submit forms with unintentionally data because KeeFox do some replacement where i really don't expect that.
Example when you register an account: http://forum.nusphere.com/profile.php?mode=editprofile

**Comment by luckyrat** [comment]
Thanks again for all the suggestions here. Before KeeFox 1.5 is released I want to have either implemented these suggestions or broken them down into more specific tasks. Feel free to raise specific issues yourself but please wait a month or two until you can take a test version of 1.5 for a spin (when #394 is merged to master).

The action URL is not helpful (we've used it to some degree in the past without success).

We already match the number of fields. Exact matches are given the most points, reducing down to 0 by the time there is a difference of >3 one way or another. We might want to adjust the actual values used here, potentially utilising negative scores for high differences in field numbers. We also might want to consider the distribution of types of field rather than just the number (a 5 text field form for a 5 password field login shouldn't be deemed a close match). Some of that could be considered part of the related enhancement #397

Note that until KeeFox 1.5 there is no threshold for relevance - KeeFox tries to fill in a form, regardless of how good a match it actually is (assuming nothing else like the form name/id blacklist prevents it). #395 addresses this.

Regarding adjusting the threshold for a valid match (up from -infinity in KeeFox <1.5 and 1 in KeeFox 1.5) I've added this issue to track the creation of an advanced option for the user to adjust it to their preference: #396

See also #398

**Comment by luckyrat** [comment]
I think everything here has either been implemented in the 1.5 beta or pulled out into a separate ticket.
