### ISSUE TITLE
Keepass logs me into the wrong Google Account

### ISSUE THREAD

**Issue by gab** [luckyrat/KeeFox#342]
I have three Google Accounts. If I log into the first one, then into the second one (without logging out the first one) and then log out (which logs out of both), something very strange happens. When I want to log back in and I enter the credentials for my first account, it logs me in my *third* account! Not only have I logged out of all google accounts but I've also tried clearing all cookies and cache and restarting the browser, and it still logs me into that third account. I've set Keefox to only fill forms not submit them, and despite Keefox's autofill filling out the fields with the username and password of my first account, I somehow end up connected to the third. Very awkward and could be considered a security issue.

The credentials entries for all three accounts have been created manually in the Keepass database and all have https://accounts.google.com as their URL.

If I follow the same steps manually after having disabled Keefox the problem doesn't happen anymore, so it's clearly an issue on the Keefox side. Doesn't happen either when using the alternate plugin PassIFox.

**Comment by datr** [comment]
Would it be possible for KeePass to detect the username that google has placed in to the login form and insert the correct password?

This is what LastPass does and seems like a better solution to me.

**Comment by konus1** [comment]
Logging into google accounts is still difficult, even pasting the password manually leeds to the wrong account.

**Comment by luckyrat** [comment]
@datr - In theory we could scrape the login page for that information. I'm not surprised that LastPass or other commercial solutions would do this for a site as popular as Google but I can't do that for KeeFox because Google could change their website at any second and I don't have the time to be able to respond to that quickly enough. At least the current solution works - a more sophisticated solution could make the process easier most of the time but at the cost of a complete failure for many days, weeks or even months when Google next change their website.

**Comment by TorKlingberg** [comment]
This happened to me too. I had to disable KeeFox, restart Firefox, log into my Google account, enable KeeFox and restart Firefox again. This is very annoying and it looks like I will have to do it every time Google wants me to re-login.

It seems that KeeFox is filling in an invisible email field that I cannot write in manually.

**Comment by gab** [comment]
I switched permanently to passIfox/chromeIpass which doesn't have this problem. Too bad, KeeFox had a more "integrated" feeling.
