### ISSUE TITLE
KeePass - keepassRPC.plgx missing

### ISSUE THREAD

**Issue by pratham2003** [luckyrat/KeeFox#348]
If the users has previously installed KeePass then the installation steps do not support using it.

I had to manually browse to Addons > KeeFox > Options > KeyPass (Tab) to set the path to KeePass installation here.

Even after doing the above the installation does not cover automatically copying the keepassRPC.plgx file to the KeyPass path.

After some searching on google I found out the keepassRPC.plgx should be in the KeyFox's extension folder in my firefox folder.

So I went to %AppData%\Roaming\Mozilla\Firefox\Profiles\{my profile}\extensions\keefox@chris.tomlinson\deps\ and ran the KeePassRPCCopier.exe. I believe for this to work the path must be set in the KeyFox addon's option in Firefox. You could manually copy the keepassRPC.plgx from the 'deps' directory to the 'plugins' directory in KeyPass.

Remember to restart KeyPass after copying the keepassRPC.plgx.

**Comment by salibhai1** [comment]
I had the same issue as pratham2003. My Keepass is portable edition.  In order to get this to work, I had to copy Keepass.plgx manually from my  %AppData%\Roaming\Mozilla\Firefox\Profiles{my profile}\extensions\keefox@chris.tomlinson\deps\.  

Please consider uploading this Plugin binary file to github.  Thanks

I also use Keepass for Chrome and they host the binary here:
https://github.com/pfn/keepasshttp/

**Comment by luckyrat** [comment]
I don't see how having to maintain a separate copy of the plugin on the internet will help. If anything it would cause more trouble because at least if you follow the instructions to copy the plugin that is bundled with KeeFox you'll be sure that you are using a compatible version of KeePassRPC for your KeeFox version.

Please open a fresh issue for any further suggestions regarding improved instructions or manual pages, etc.

**Comment by Sqwrly** [comment]
I agree this is an issue. I just spent the last hour digging through here trying to find where to get the plgx file. Not very clear.

**Comment by dlech** [comment]
> Please open a fresh issue for any further suggestions regarding improved instructions or manual pages, etc.

**Comment by Sqwrly** [comment]
Further means in addition to what already exists. This suggestion already exists. My apologies.

**Comment by cracket** [comment]
Unfortunately people still struggle with this problem. GUI does not notify about specifics of this problem, so deeper investigation is needed. On my computer KeeFox generated 1GB log with repeating error about version 67072 - which one is that? As I understand version is not passed between RPC plugin to FF as human readable string?  In better world I would get comprehensible info on GUI:
`Connected to KeePass in directory C:\xxxxx  which contains KeeFoxRPC plugin version 1.2.3.4, expected version 1.3.5.7. Please update KeeFoxRCP.plgx manually in directory C:\xxxxxx\plugins to version 1.3.5.7`

This is a workaround for another issue that plgx file was not installed successfully, but I guess this would make our life easier.
