### ISSUE TITLE
Keefox 1.4.5 no longer catching pw dialogs on TB 31.3.0

### ISSUE THREAD

**Issue by Freddy97** [luckyrat/KeeFox#351]
I updated today Keefox from 1.4.3 to 1.4.5, first on FF, then on TB (34.0.5 / 31.3.0), both in en-us. I'm using Win7. With FF, Keefox works properly, as before the update. 

But with TB, password dialogs for POP accounts are no longer catched (extended) by Keefox when requesting "Get all new messages", i.e. Keefox neither autofills the dialogs nor inserts a button to login into Keepass. On the other hand, no problems when examining an IMAP account (a dropdown to select a Keepass entry is added to the pw dialog). I have around 5 pop accounts and 10 imap accounts. 

P.S. This sounds like the issue #341, but as mentioned, I'm using en-us, thus unrelated to locale.

P.S.2: The only error found in the log is the following (when starting TB):
```
Failed to create KeeFox widget because: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://keefox/content/panel.js :: keefox_win.panel.construct :: line 50"  data: no]
```

Any advice ? Thanks in advance !

**Comment by Freddy97** [comment]
P.S. Sounds like the issue #341, but as said, I'm using en-us.

**Comment by Freddy97** [comment]
PS.PS: The only error i can see in the log is the following (when starting TB):
Failed to create KeeFox widget because: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://keefox/content/panel.js :: keefox_win.panel.construct :: line 50"  data: no]

**Comment by Freddy97** [comment]
P.S.3: If I comment out the lines commonDialog.js:305 and :306, Keefox runs fine in TB:
// titles[aDialogType] = titles[aDialogType].replace ...
// prompts[aDialogType] = prompts[aDialogType].replace ...

**Comment by dlech** [comment]
This was broken by a0bafc171ba2244a248b7cc0e5931ce338dd1a47, so this commit needs to be reverted and we need to try again to fix #229.

**Comment by dlech** [comment]
I've managed to fix this. Hopefully @luckyrat will have time to do yet *another* release soon.

**Comment by luckyrat** [comment]
The fix is available now in 1.4.6b1: https://github.com/luckyrat/KeeFox/releases/tag/v1.4.6b1

I'll put that on the AMO beta testing channel in 12-24 hours assuming I hear some feedback from Thunderbird users here that it actually works correctly now.

I'll push it to the stable release channel a day after that unless I hear of any new problems. Mozilla were remarkably quick reviewing the update to 1.4.5 so fingers crossed that the small and simple changes in this version mean 1.4.6 will have the same smooth passage through the process but who knows - the average time at the moment is 6 weeks but if it takes over a week this time I'll ask nicely for a quick review since it's a fix that will affect a group of users.

**Comment by AW-UC** [comment]
Same problem here, but with IMAP account. Version 1.4.4 worked fine. In 1.4.5 and 1.4.6 I get a prompt for Mail-Server Password. Fields for remote calendars and adressbooks are filled fine, though.

**Comment by dlech** [comment]
@AW-UC, are you the same person from [this discussion](https://discussions.zoho.com/keefox#Topic/71684000000658005)? If not, what Thunderbird version and locale are you using?

It is expected that SMTP would have been broken in 1.4.5, but working in 1.4.6. IMAP should be working in all versions. So, we need to figure out what is different about your install so that we can reproduce the problem.

**Comment by AW-UC** [comment]
@dlech No, I'm not that person but it seems to be exactly the same problem. I'm using german TB 31.3.0.

**Comment by Freddy97** [comment]
Hi David + Chris,
Version 1.4.6b1 fixes the issue I reported here: Keefox autofills again all prompts in TB 31.3.0 (en-us), in particular dialogs for POP3. Sending Email is working fine as well (I didn't check if it was broken in 1.4.5).
Many thanks for your immediate reply & support !
Freddy

**Comment by dlech** [comment]
It turns out that the matching broke for German/IMAP specifically because unlike other translations, it has dashes ("Mail-Server-Passwort") which were incorrectly included in the the list of regex characters in #344.

**Comment by luckyrat** [comment]
OK, https://github.com/luckyrat/KeeFox/releases/tag/v1.4.6b2 should work now for all locales. Please try it and let me know if it's OK to push this to all beta users.

**Comment by AW-UC** [comment]
Version 1.4.6b2 fixes my issue. Great!

**Comment by crazy-max** [comment]
Version 1.4.6b2 fixes the problem for me too on Thunderbird (french) 31.3.0.
Thx :)

**Comment by snodo** [comment]
german thunderbird user here
after 1.4.5 didn't work, I found these threads and tried 1.4.6b1 which didn't change anything
finally 1.4.6b2 fixed the bug - thanks!

**Comment by luckyrat** [comment]
Thanks for the feedback everyone. I've now pushed 1.4.6b2 to all beta channel users: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/

I'll do a stable release in a couple of days if no serious problems emerge during beta testing.

**Comment by crazy-max** [comment]
Thanks @luckyrat ;)

**Comment by AntonStoeckl** [comment]
1.4.6b2 works for me also in TB 31.3.0 (German)

Thx! :+1:
