### ISSUE TITLE
Entries are not saved with custom port

### ISSUE THREAD

**Issue by ceribik** [luckyrat/KeeFox#358]
E.g. If i store a login for http://foo:8080, the login is stored under the site "foo" as opposed to "foo:8080".

This is important if you have multiple services, e.g. http://foo:8080 and http://foo:8081

**Comment by TerryD3** [comment]
Im learning I don't know where I will be I have to keep my e-mail address because im disabled and all my doctors,lawyers,have this e-mail 

     On Tuesday, January 20, 2015 12:52 AM, ceribik <notifications@github.com> wrote:
   

 E.g. If i store a login for http://foo:8080, the login is stored under the site "foo" as opposed to "foo:8080".This is important if you have multiple services, e.g. http://foo:8080 and http://foo:8081—

**Comment by luckyrat** [comment]
This appears to be limited to HTTP Auth password saving (which is relatively rare and hence explains why it's not been spotted before).

We do have access to the full information and even launch the search for existing passwords using that but for some reason just store the host portion of the URL only.
