### ISSUE TITLE
KeeFox makes one tab invisible

### ISSUE THREAD

**Issue by KORraNpl** [luckyrat/KeeFox#366]
I have strange issue with KeeFox enabled - every time I start Firefox with some tabs, "Setup KeeFox" appears and one tab is invisible so there are two ways to get it - close all visible tabs or ctrl + tab to it. [Here](http://imgur.com/48kVKJf) is the screenshot - in this case about:addons is invisible. KeeFox and KeePass are configured and running OK.

Firefox 35.0.1, KeeFox 1.4.6, KeePass 2.25, Linux Mint 17.1 “Rebecca” MATE

**Comment by luckyrat** [comment]
Are you sure it's KeeFox that causes the invisible tab?

What happens if KeeFox is your only enabled addon?

Does KeeFox work despite showing the "setup KeeFox" page?

Are you sure you haven't got that "setup KeeFox" page stored as a tab that you want to be opened each time you start Firefox / go to your home pages?

Do you know if Linux mint customises the Firefox theme and behaviour like Ubuntu?

Thanks,
Chris

**Comment by KORraNpl** [comment]
I pretty sure it's KeeFox fault. I just tried to launch Firefox with only KeeFox enabled and problem is still present.

KeeFox works like a charm.

"Setup KeeFox" is not a tab that I want to be opened. My setting for startup is "Show my windows and tabs from last time". When I don't close "Setup KeeFox" tab before closing Firefox, next time I start the browser there is second "Setup KeeFox" tab.

I have no idea if there are any customisations in Firefox.

**Comment by luckyrat** [comment]
Does it make a difference if KeePass is already running when you start Firefox?

Can you post a debug log file of your startup process? https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options-%7C-Logging

**Comment by KORraNpl** [comment]
No, problem is there no mather if KeePass is launched or not.

Here you can find log of three starts of Firefox: http://pastebin.com/dechvFAf

**Comment by luckyrat** [comment]
Looks like you may have moved your KeePass from the default location:

> Sun Feb 22 2015 15:28:34 GMT+0100 (CET):DEBUG: Did not find /home/korran/KeePass/KeePass.exe

Either run KeePass from that location or edit the setting: KeeFox options / KeePass / KeePass installation location.

**Comment by KORraNpl** [comment]
It was installed by default in /usr/bin/, after I edited KeePass installation location and marked "Remember settings above" (it was necessary) the problem is solved. Thank you!

**Comment by luckyrat** [comment]
Great. Glad it's fixed!

"Remember settings" shouldn't be needed. Maybe it's a Linux thing but it would be helpful if you could say where you put the KeePassRPC.plgx file. Is it in a "plugins" subdirectory?

**Comment by KORraNpl** [comment]
Correct, exactly as your tutorial in "Setup KeeFox" says, I put it in /usr/lib/keepass2/plugins/.

Without checking "Remember settings" KeePass location was cleared everytime I closed window with setings.

**Comment by slovdahl** [comment]
I have also been experiencing the invisible tab issue since I started using KeeFox about a year ago. Today I finally got fed up with the "Setup KeeFox" page showing every time I start Firefox, so I looked through the settings and configured the KeePass install location correctly and it solved the problems, invisible tab and "Setup KeeFox" page both disappeared.

So I still think it's a bug in KeeFox. If the "Setup KeeFox" page is shown when starting Firefox, there will always be an invisible tab.

I'm also using Linux, and this happens on on two different Ubuntu 14.10 machines with Firefox 36.

**Comment by Metal-Mighty** [comment]
Just wanted to report the same problem here.
I switched to Linux recently and Keefox won't remember where the install directory is as long as you don't check the "Remember above settings" box after filling in the install directory field.
I always had my second pinned tab hidden since then but never thought it was because of Keefox, even less because of the Setup page popping everytime. I didn't take care about it before because Keepass was recognized anyway.

I share my Firefox profiles with my Windows install, so I guess someone should try on a clean profile to see if it has any impact. But even after many reboots without starting Windows, problem happened.

System: Firefox 36, Linux Mint 17.1 Cinnamon 64bits / Keepass 2.25

**Comment by qw3ry** [comment]
I can confirm the problem.
Would it be an option to check /usr/bin/ by default if keepass is not found and remember the install location? It would be nice if this problem would not occur by default (I installed KeePass via PPA and it automatically installed there, but I don't know if there is another preferred installation method)

**Comment by openpaul** [comment]
Same Problem here (xubuntu 15.04 FF 39, keefox 1.4.8.1)

It occurs only (I guess), when keepass is not started yet. Then the keefox page (chrome://keefox/content/install_mono.xul) opens and a hidden tab is created. Sometimes the hidden tab has content, sometimes its empty.

**Comment by elfalem** [comment]
Also having the same issue on Linux Mint 17.1. Had to check "Remember settings".

**Comment by f4grx** [comment]
Same as others. linux mint 17, firefox 40, etc.

it is interesting to note that keefox works even if this install location is not set

why do we need this in the first place? to autostart keepass if not started?
then, keefox should just warn that keepass could not be started.

the invisible tag is quite boring.

**Comment by fhackenberger** [comment]
@luckyrat Could you please check if there is a way to fix this on Linux. I'm using keepass in its default location /usr/bin/keepass2, when launched I can see that Mono runs it like this: _/usr/bin/cli /usr/lib/keepass2/KeePass.exe_. If I set my install location to _/usr/lib/keepass2/KeePass.exe_ this bug is gone, as well is #608

**Comment by ronnihh** [comment]
I can confirm that this issue also effects Windows 8.1. Have just tried setting installation folder, and will report back if this solves it here as well.

**Comment by JamesHealdUK** [comment]
Firefox 52 on Ubuntu GNOME 16.10, tried reinstalling but no results.

Weirdly, Keefox works fine, so I dont know why that tab shows up every time I start Firefox as its already been configured and installed.
