### ISSUE TITLE
Detached labels in options dialog

### ISSUE THREAD

**Issue by tspivey** [luckyrat/KeeFox#384]
In the options dialog of KeeFox, some of the labels are not attached to their controls.
When using a screen reader, this means that I can't easily tell what a control is for. For example,
in the finding entries tab, I simply hear: combo box fill in and submit the form collapsed
Reading the [XUL accessibility guidelines](https://developer.mozilla.org/en/docs/XUL_accessibility_guidelines),
it looks like just using the label tag should fix it after associating it with the control. See the section Form labels.

If I take the first one from the Finding entries tab:
```
            <description id="desc-when-user-chooses">%-KeeFox-pref-when-user-chooses.desc-%: </description>
```
And change it to:
```
            <label control="KeeFox-pref-matchSelected-list" id="desc-when-user-chooses">%-KeeFox-pref-when-user-chooses.desc-%: </label>
```
My screen reader now automatically says the label for that control:
When I choose a matched password, KeeFox should: combo box Fill in and submit the form collapsed

What are the visual effects, if any, of doing this? It would be nice to get these fixed in the official addon.

The controls I've found so far that aren't labeled are:
1. The three combo boxes in the Finding entries tab.
2. The combo box in the Logging tab.
I also think that the Select where you would like KeeFox to record a log of its activity and the options under it should be part of a group, but I'm not sure on that.
3. Connection Security: Two combo boxes after the link "Learn more about these settings and the communication between Firefox and KeePass in the manual".

**Comment by luckyrat** [comment]
I'll take a look and get it in the v1.5 release provided there are no detrimental visual or behavioural changes (if there are, we can still investigate a way to do it, it just might take more time).

**Comment by luckyrat** [comment]
I've made a lot of progress on this for KeeFox 1.5 but will hold off calling it complete until I can get feedback on how it works in the real world.

I've done the three combo boxes on the finding entries tab. I now remember considering this when I first wrote KeeFox but was unsure how to sensibly represent the visual table-like structure of the 2nd and 3rd combo boxes which allows "When KeeFox chooses a matching login for:" and "KeeFox should:" to be written once and shared for both combo boxes. I've just guessed at what will work this time since it sounds like anything is better than nothing.

The combo box in the logging tab was straight forward and I've put the checkboxes into a groupbox as you suggested (note that I have removed the "alert" option for KeeFox 1.5 though).

I've added labels for the two combo boxes on the connection security tab too but I'm not sure whether the overall layout makes sense. Each combo box has a label which now should clearly say what it is for but I'm not sure where the explanatory tip fits into the process. Hopefully it's just read straight after the combobox in a way that is associated with the setting you've just heard (it is displayed visually directly underneath the combobox). In theory I think a groupbox is the way to go here too but the visual effect of a combobox is going to be too much of a problem since I've just had to cut down on vertical space usage already to get everything to fit in on small screens with verbose languages so there's definitely no spare vertical room for extra elements.

I'll post another update when there is a beta version ready for testing (won't be for a month or so at least).

**Comment by luckyrat** [comment]
In case you missed it, the v1.5 beta is now available at https://addons.mozilla.org/en-US/firefox/addon/keefox/#beta-channel

Please let us know if it's working as expected.

**Comment by tspivey** [comment]
Seems to be. When I tab through, I hear:
When I choose a matched password, KeeFox should:  combo box  Fill in and
submit the form  collapsed
However, the next label isn't as clear:
A standard form  combo box  Fill in the form  collapsed
I'm missing the context, which I believe is "When KeeFox chooses a
matching login for:". Should that possibly be a group? I'm not sure.

**Comment by luckyrat** [comment]
I don't think it could be a group because there are two pieces of context required, one for the label and one for the combo box. It's visually laid out in a tabular format: 3 columns and 2 rows, with the left-most column containing the context for each row ("When KeeFox chooses a matching login for:" on the top row and "KeeFox Should:" for the bottom row).

Conceptually we want the reader to prepend the corresponding left-most cell contents in front of each of the other cells so that the actual words spoken are:

"When KeeFox chooses a matching login for A standard form, KeeFox should combo box Fill in the form collapsed"

and then the next field would be:

"When KeeFox chooses a matching login for An HTTP Auth, NTLM or proxy prompt, KeeFox should combo box Fill in the login prompt collapsed"

There's also a 3rd piece of context displayed underneath the two rows which explains that both settings can be overridden in the settings for a specific KeePass entry.

I think the only way to make this sound clearer is to completely change the visual interface by splitting some options into another separate tab so that we can still fit everything onto a small laptop screen.

I think the current visual interface is clear but I generally subscribe to the idea that any interface that can't be clearly described by assistive technologies is too complicated so I have to assume that I'm under-estimating the complexity for many other users too. Therefore I have re-designed the layout in a way that will hopefully make sense to everyone.

I'll release a new beta with this change in a week once the translation team has had a chance to make it work in their respective languages. You should now get the update automatically so please offer feedback once you've had a chance to try it out.

**Comment by luckyrat** [comment]
Actually I've put a release with this change here: https://github.com/luckyrat/KeeFox/releases/tag/v1.5.3b8

But Mozilla's new requirement for add-on signing might make it too much hassle to test it from github so don't worry if you'd rather wait for the automatic update next weekend.
