### ISSUE TITLE
Thunderbird 31.6: Password manager safe password check field hidden after removal of Keefox plugin

### ISSUE THREAD

**Issue by rkolless** [luckyrat/KeeFox#389]
Hello,

I installed Keefox 1.4.6 on Thunderbid 31.6 and removed it later to switch back to the internal password manager of Thunderbird.
Since the installation and removal the checkbox in Options->Security->Passwords does not exist anymore and I have to type the passwords all the time except the passwords which already existed in the internal password manager list before I installed Keefox.

![image](https://cloud.githubusercontent.com/assets/5840426/6996454/d392b69c-db89-11e4-89ad-a5fbc369ff21.png)

I was unable to restore the old situation and I would like to avoid to remove my complete Thunderbird profile folder.

**Comment by rkolless** [comment]
The default password entry field does not show the password save checkbox also:

![image](https://cloud.githubusercontent.com/assets/5840426/6996593/766a431a-db91-11e4-9b2b-8c7ca642fcc8.png)

**Comment by luckyrat** [comment]
This looks like a bug in another addon you have installed or maybe even Thunderbird itself (although such a fundamental bug is very unlikely).

**Comment by rkolless** [comment]
I just have Enigmail and Lightning installed but I found out where the problem currently.

The value user_pref("signon.rememberSignons", false); in the prefs.js was set and that is the reason why the internal password manager did not ask.
Currently I can´t say which task that I or a any software did changed this value.
Removing the value solved the problem.

Would it be useful for KeeFox to check for this value during deactivation/removing and warn for a disabled internal password manager prompt?

**Comment by luckyrat** [comment]
KeeFox sets that setting to false on install and there's not a reliable way to change it back during disable/uninstall (but if there were I'd definitely do it).

The setting is controlled by the checkbox that is not visible on your system. With the setting false, the checkbox will still be visible (just unchecked) so there must be a bug with another addon or with Thunderbird itself if you can't see that checkbox unless the corresponding value is true.

**Comment by rkolless** [comment]
Ok, I could reproduce it and the setting in prefs.js you set hides the checkbox in the password prompt (2nd screenshot).
Deleting the value completely and setting it to the default value restores the checkbox.
You can ignore my screenshot in the first comment. TB does not provide this checkbox, I mixed this up with Firefox.

I am a little bit curious why KeeFox can add a value but can´t delete it if it has been set by itself?

**Comment by luckyrat** [comment]
If KeeFox has been disabled/uninstalled then it can't run any code to alter
a value regardless of whether it was the most recent code to modify it.

**Comment by rkolless** [comment]
In this case a notice should be given or the possibilty to enable the internal password manager with a checkbox in the properties of KeeFox.
An uninstallation task which does not clean up alteration outside of the plugin in TB is not the best solution.

**Comment by luckyrat** [comment]
Sorry, but we can't put a checkbox to enable the internal password manager within KeeFox's options because that has the same effect as offering the user an option to break KeeFox (which is obviously just going to result in a lot of confused and upset users).

I wish we could offer the user a way to re-enable the setting when they disable/uninstall KeeFox but it's not something the addon system can do reliably, at least at the moment. I've seen that the latest Nightly build of Firefox is deprecating the faulty feature that was supposed to offer this capability so we can hope that a new Firefox and Thunderbird version this year or next will allow us to improve this situation.

**Comment by dlech** [comment]
Here is a possible solution: http://www.codeproject.com/Tips/142614/JavaScript-listens-to-Enable-Disable-event-of-an-e

**Comment by luckyrat** [comment]
The problem I found with all the methods to do this is that they only work for SDK or bootstrapped add-ons. I think the best-case scenario would be if there is some new API since the FUEL/Firefox 4 era which will tell us that the browser is shutting down and the addon will be removed on startup. We could then race Firefox's shutdown process to execute some cleanup code - it would probably be able to finish executing at least some of the time since it will be pretty basic stuff, dependant on a tiny bit of disk access at worst (we could also fire an "uninstalling" event to the metrics server once we've done the essential work but that's low priority and even less likely to win in the shutdown race because I expect opening new network connections during shutdown is unlikely to be successful).

Even so, we'd still have the issue of what happens if the removal is aborted (e.g. when Firefox crashes on shutdown or the add-on uninstallation fails for some reason - I've seen problems upon addon installation so there might be similar bugs that can affect uninstallation). Still, something is probably better than nothing provided we can be sure we'll never make the situation worse than it already is.
