### ISSUE TITLE
KeeFox loses focus when any other  tab is reloading

### ISSUE THREAD

**Issue by Fossius** [luckyrat/KeeFox#390]
Firefox 35+

**Comment by luckyrat** [comment]
Please explain what you mean in more detail and what your OS version.

**Comment by Fossius** [comment]
win7x64 
![i](https://cloud.githubusercontent.com/assets/7037530/7179561/f70a16c2-e441-11e4-813a-558c5fa989d3.gif)

**Comment by luckyrat** [comment]
Thanks for the detailed example.

I can't replicate exactly the same situation on my machine so there might be another addon or theme that is affecting your system differently. 

The KeeFox panel does not disappear for me. However, I do see that the login for the current page disappears which should not happen.

I am rewriting all the code that puts logins into that panel as part of a massive process to get KeeFox working with upcoming Firefox versions. Therefore I won't look into this now because it is possible / likely that the behaviour will be fixed by this other work. I'll keep an eye on this so we can reassess the situation later this year.

**Comment by Fossius** [comment]
Thank you for great addon.

**Comment by luckyrat** [comment]
Is this fixed in v1.5.3?

**Comment by Fossius** [comment]
Yess!! Thank you!
