### ISSUE TITLE
RegEx only working if URL field of the entry has at least one character

### ISSUE THREAD

**Issue by garyee** [luckyrat/KeeFox#393]
Hi,

great project!
There is just one thing and I do not know if this behavoir is intentional:
I am working a lot with wordpress. To log in into the backend you will have to append "wp-login" to the url of the site. So I have a pool of passwords (5) for all the sites (20+) I work on.
So I put all the passwords into Keepass and put in the regex \/wp-login\/$. But I regconized that Keefox only found the entries if I fill something in the url-field of the Keepass entry, even if it was just "www".
It is not a big Bug, but it was getting a bit anoying as Keefox kept filling fields in, on the site which url was in the url field of an entry and when I did empty the url-field it did not work anymore.

**Comment by luckyrat** [comment]
Yeah it's by design that there must be a URL for an entry for KeeFox to see it. Without it, the "one-click" login feature would not work. I'll take a quick look to see if it's now possible to relax this requirement in some cases but I will abandon the change if I spot any side-effects or if it will take too much time.

**Comment by luckyrat** [comment]
I think this behaviour can be improved when #412 is implemented. Once we have more detail about the relevance of the match from KeePassRPC, we'll be able to consider a login a match for a form even if it has no fixed/standard URL. Given that we offer people an option to completely hide an entry from KeeFox, I think the side-effects of such a change will be pretty minimal. If it's a simple change I'll bundle it into the #412 work - if not I'll create a new ticket specific to that task and reference it from #412 so please watch that issue for updates.

The search and list of all logins will still be limited to those logins which have an exact URL because both of those features lead to the one-click login functionality which will not work for any login which does not have a URL to load in the browser.
