### ISSUE TITLE
Allow "fill form" option for unmatched logons

### ISSUE THREAD

**Issue by thx1200** [luckyrat/KeeFox#431]
Consider a scenario where you use one common logon for multiple sites, such as a Disquss type of system where you need to log in to post, but the URL could be anything that implements the same system.  Rather than adding each and every URL to additional URLs, a nice feature would be able to select "fill" after searching logons.  Right now, if you left-click an entry when you search, it goes to the primary URL.  And if you right click, you get "edit login."  It would be good to have a "fill form" button so you could use that usernamen and password to fill in any arbitrary username and password field.  Of course, sometimes the field names may not match, but that is easier to deal with than adding many URLs since field names tend to not have a lot of variety.

**Comment by thx1200** [comment]
I should point out that this could maybe also be used in situations where "Detect Forms" fails, which I have encountered before too.

**Comment by luckyrat** [comment]
I probably won't implement this suggestion because of the risk associated with credentials being submitted to the wrong website. In the worst case this feature could be abused by a malicious website that tricks a KeeFox user into forcing their credentials into a phishing website.

In situations where the shared login system follows a common but unique URL pattern, a regular expression could do the job (although obviously that's a little too technical for many users at the moment). In most other situations I think #109 would be helpful enough to avoid the need for this feature.

**Comment by thx1200** [comment]
RegEx did the trick.  I can't believe I missed that was even an option.  Thanks.
