### ISSUE TITLE
Where is the Database?

### ISSUE THREAD

**Issue by Hwy101** [luckyrat/KeeFox#434]
Where is the Path to the Database?

Firefox is NOT connecting to it.

I keep getting the Launch KeeFox button. Any thoughts on this?

Thanks

**Comment by luckyrat** [comment]
I'm not sure what you're asking. Maybe try reading this first: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting

**Comment by Hwy101** [comment]
Simple: What is the Path to where the database is Installed!

**Comment by Hwy101** [comment]
I was very specific:
I have asked twice for the path to where the database is installed.
Are you going to support/answer?

**Comment by Radagast** [comment]
Unfortunately, your question is short on specifics. However, I assume by "database" you're referring to the the location of your keepass database, which you can find where ever you created it.

**Comment by luckyrat** [comment]
Yes as @Radagast says, the problem is that your specific request for a "database path" doesn't make any sense in the context of KeeFox.

KeeFox does not install a database so if you're looking for the path to your KeePass database, only you can answer that question.

If you are more interested in understanding why you are only seeing the "launch KeePass" button (so KeeFox has no connection to KeePass) you should start with the [getting started tutorial](http://tutorial.keefox.org) and if the tips there don't help, move onto the troubleshooting guide which is highly likely to answer your question and if not, you'll at least have a better understanding of the sort of information you'll need to search the forums for or put here for us to be able to help you resolve your specific problem.

**Comment by Hwy101** [comment]
See I do NOT even know how to ask a question (I guess that happen when you get to be 70 and the stuff you are trying to do is complex) <sigh> Remember you are writing from the Developer's Eyes, I am not. You see things I do NOT.

I hope the getting started is be than the 'KeePass' is not connected to the Database... (leading to my Bad question)

PS - I tried  'Migration' talked about (for AIRobo from Siber Systems) - Did NOT work, even using the '*.*' to Import ALL -but, then I am SURE I am wrong 'somewhere' -just like my bad question.

**Comment by luckyrat** [comment]
Not sure where we got to here but note that the new version of KeeFox (1.5.3) comes with a new getting started tutorial and improved troubleshooting advice so give that a try if you're still struggling.
