### ISSUE TITLE
"Login with KeeFox" right-click-menu option

### ISSUE THREAD

**Issue by frederiksnijder** [luckyrat/KeeFox#436]
Would it be possible to implement the following?
* right click on a login- or password-formfield (or perhaps somewhere else on webpage) and then click something like "Login with KeeFox"
* this would then open the Keepass window
* after unlocking the database Keefox would then enter the website username and password in the form fields and login

Currently, after logging in to the database you have to rightclick and select the login anyway. So this saves a few mouse clicks. (And, this way you can also disable "Display a notification bar when you need to log in to KeePass database" so that it doesn't show up on any webpage with forms.)

**Comment by luckyrat** [comment]
It might be possible but I'm not sure I'm a fan of the idea because you are essentially telling KeeFox to perform an automatic behaviour before it is even certain what data will be available to choose from (e.g. what if you accidentally log in to the wrong database?) And what should happen when KeeFox finds more than one possible login to put into the form?

If you're keen on saving mouse clicks and avoiding the notification bar (which is disabled by default in KeeFox 1.5 anyway) you could use the keyboard shortcut (ctrl-shift-2) to launch KeePass whenever you're ready and then press it again to initiate the auto-fill operation.

It sounds like #204 might be of interest to you too - it won't launch KeePass but could still be potentially useful for your workflow.
