### ISSUE TITLE
Support for Firefox mobile

### ISSUE THREAD

**Issue by SnowGabe** [luckyrat/KeeFox#445]
Keefox isn't available for Firefox on Android. Can you port the extension to mobile? I've tried changing "extensions.checkCompatibility" preference, but installing still isn't possible.

**Comment by luckyrat** [comment]
Unfortunately it would need to be a completely different addon which no-one has yet had time to develop. There's going to be almost no overlap between a mobile and desktop version because on mobile:

1. There is no KeePass program running in the background executing the KeePassRPC.plgx plugin
2. The user interface will need to be replaced
3. The core functionality will need to be re-written with a focus on only basic features in order to keep memory/processor/battery usage down
4. The mobile version of Firefox does not have support for the features KeeFox is built upon

I just use KeePass2Android's "Share to" feature to load the password keyboard but I'll admit my need for mobile web browser login functionality is very low so my motivation to spend a few years developing a solution to save a few seconds per day is not high.

Thanks,
Chris
