### ISSUE TITLE
Install Page won't load the bar

### ISSUE THREAD

**Issue by axi92** [luckyrat/KeeFox#456]
I stuck on the page (chrome://keefox/content/install.xul) and the bar won't fill up.
Is it maybe I'm behind a proxy?

https://github.com/luckyrat/KeeFox/wiki/en-|-Getting-started#manual-installation
Where do I get the "KeePassRPC.plgx"?

**Comment by luckyrat** [comment]
In theory a proxy could do this (although probably only a badly configured one and normally it would fail rather than get stuck).

It might be a temporary problem. You could clear your browser cache and try again.

If that doesn't work, you can find the plgx file in your user profile folder. I have updated the [getting started page](https://github.com/luckyrat/KeeFox/wiki/en-|-Getting-started#manual-installation) with more detail about where to find this file so please let me know if you still have trouble locating it.

**Comment by luckyrat** [comment]
Looks like this is the same problem as #457
