### ISSUE TITLE
KeeFox isn't downloading files when I want to install it

### ISSUE THREAD

**Issue by vitushoesl** [luckyrat/KeeFox#457]
Hello,

I just discovered your add-on a few days ago and it would be great for me to use - but the installation doesn't work for me.

When I try to install it it always says "downloading files" but it never finishes (even after 2 hours). I tried it on windows 8.1 and windows 10 - whats wrong?

![2015-05-26 12_44_50-keefox installieren](https://cloud.githubusercontent.com/assets/12609156/7810746/17850a4c-03a5-11e5-9398-a536f203744f.jpg)

**Comment by luckyrat** [comment]
It looks like Firefox has broken this part of KeeFox :-(

Strangely, Mozilla [claim it's been broken since Firefox 36](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWebBrowserPersist#saveURI%28%29) but this morning seems to be when people have started reporting the problem (many months later).

I'll try to find a new way to do the download but it can take Mozilla months to publish add-on updates so you'll probably want to do a manual installation in the time being: https://github.com/luckyrat/KeeFox/wiki/en-|-Getting-started#manual-installation (that should just be a case of downloading and installing KeePass separately)

**Comment by vitushoesl** [comment]
It's me again - did the manual installation a few minutes again and after that everything works great. I hope this helps you by fixing the error.

**Comment by axi92** [comment]
Manualy worked =)

**Comment by luckyrat** [comment]
Thanks for the feedback.

I've pushed out a beta version that fixes this problem and will push 1.4.8 to all users today or tomorrow if no unexpected problems come up. With luck it'll be approved by Mozilla more quickly than the previous 10 week approval process but you just never know.
