### ISSUE TITLE
new notificationManager (notificationManagerWin.js) in v1.5 breaks Thunderbird

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#463]
The main problem with this is that `window.gBrowser` does not exist in Thunderbird.

Either we need to disable notificationManager in Thunderbird or modify it to use something other that `window.gBrowser` if `windows.gBrowser` does not exist.

Thoughts?

So far, I have added a bunch of `if (window.gBrowser) { ... }` to get it working, but this does not seem like the best solution.

**Comment by luckyrat** [comment]
Well we previously decided that Thunderbird had never used the old notification code (hence I was able to delete _getNotifyBox() ) so I think it's fine to disable the new one too.

Getting some kind of notification system to work in Thunderbird should probably be considered an entirely separate new feature since we'd have to think about which notification features make sense within there. Apart from some kind of password saving feature, the main thing that comes to mind is the connection error messages that can provide the user with more information about why KeeFox is not connecting to KeePass. They're obviously not essential but might be very handy especially for new users that are uncomfortable poking around in the logs.

We've got some `if (window.gBrowser) { ... }` in other places already but if it's easy then it might make more sense to create something like `if (keefox_org.utils.runningInABrowser())` to more clearly explain what we're doing without resorting to comments every time. I'll leave it up to you since you're already playing around with those bits (obviously getting it to work at all is a higher priority).

**Comment by dlech** [comment]
I was able to get Thunderbird working again with minimal changes.

About the `if (keefox_org.utils.runningInABrowser())` idea. Good idea, but I kind of like just using `if (window.gBrowser)` because then I know that if there is `window.gBrowser` inside of the if statement, then it is legitimate, otherwise it can be removed.

**Comment by luckyrat** [comment]
Looks good. Thanks.
