### ISSUE TITLE
Suggestion: Remember last search

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#481]
Using v1.5.1b1 - trying to log in to the KeeFox forum actually. I found that this is one of the sites that can't find the existing login, so I used the KeeFox toobar button in Firefox to search for my KeePass entry. If found it and I used the new feature to copy the username from this entry without having to switch to KeePass. Very nice! Pasted the username, then opened the KeeFox icon again and found that I had to search for the same entry again so that I could copy the password. Not so nice.

So, I think it would be good if the KeeFox icon remembered your search and showed the same results when you open it again.

**Comment by luckyrat** [comment]
Yeah I think so too. I deliberately avoided this feature because I wanted to see how the filtering by current website feature would shake out (at one point I considered making that the default view upon opening the panel). But now that's settled and I've used it for a bit, I've experienced this same frustration.

It'll need a bit of thought to make sure we still reset the string at sensible points (e.g. a KeePass database change? tab switching? switching to/from all/current website search mode?) Plus there might be issues with the length of the panel if it is initially opened with more content than can fit on the screen (there are some complicated Firefox bugs relating to the panel sizing, scrollbars, etc. but hopefully they won't be a problem for this). Ideally we'd retain keyboard focus across the reload too but that might not be practical initially.

I'm going to track it for v1.5 since I think it would be very worthwhile to get it implemented during the beta testing period but I won't be able to give it as high a priority as fixing bugs and if it turns out to be a big job that will delay getting an e10s-enabled version released, we should punt it to v1.6.
