### ISSUE TITLE
Thunderbird Compatiblity in 1.4.x

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#489]
Thunderbird 38 was released yesterday, although automatic updates have not been turned on yet. Either we should backport the fix from #466 to the 1.4.x series or mark it as not compatible on AMO.

**Comment by luckyrat** [comment]
I don't know if it's possible to mark as incompatible anymore, at least if it's the same behaviour as Firefox. I've just looked and it is listed as compatible up to FF and Thunderbird 37.* so I think it's doing the usual behaviour of: "assume it works until it fails an automated AMO compatibility test (which it hardly ever will because those tests are very incomplete)".

We might be able to release another stable 1.4.x version if you issue a pull request with a backported fix but there would be no guarantee that it would ever be released (if it takes a couple of months and 1.5 is ready before then, it'll be deleted from the review queue). A 1.4.x beta would be fine but since 1.5 will be ready for beta in about a week I'm not sure if it's worth it (but I speak without knowing the complexity of building and testing the backport so feel free to go ahead if you think it's a worthwhile distraction from our 1.5 efforts).

**Comment by dlech** [comment]
> I don't know if it's possible to mark as incompatible anymore

Sure it is. On AMO, log in and "Manage" your addons and select KeeFox. In the menu on the left, there is an option for "Manage Status & Versions". Select that, then select the version you want to edit. You are able to set the max version from there.

Based on what you have said, I think this would be the best course of action.

**Comment by luckyrat** [comment]
That setting is already "37.*" so if the setting had any effect, we would already see the latest Firefox and Thunderbird versions blocked. I believe the setting has been redundant since Firefox 10.

**Comment by luckyrat** [comment]
I increased the Firefox max version to 39.* yesterday on the off-chance that this somehow triggers a re-evaluation within AMO such that they pay attention to the 37.* setting for Thunderbird but I don't hold out much hope.

**Comment by luckyrat** [comment]
I don't think there's anything more I can do here. There has since been an auto-version-compatibility update for FF39 and the AMO bug preventing the v1.5 beta release has just been fixed so although it's not ideal, there is at least some hope that Thunderbird 38 users will be able to stumble upon a working KeeFox version.
