### ISSUE TITLE
How to undo "Never for this site"?

### ISSUE THREAD

**Issue by ezeeyahoo** [luckyrat/KeeFox#506]
I accidentally clicked "Never for this site" button. How to undo this action?

**Comment by luckyrat** [comment]
Open the KeeFox Options panel and click on a "site-specific settings" link (should be on the first tab but is also on others in varying places depending on your KeeFox version).

Then just find the site you want and either remove the whole site configuration or just enable the "offer to save passwords" checkbox and save the change (the latter approach will allow you to retain any other custom settings you've made for that website, although it's unlikely you have done this since you didn't know about this feature previously so just "remove site" should be fine in this case).

**Comment by ezeeyahoo** [comment]
Thanks for help...Does KeeFox works with daily build of KeepassX2Alpha6? Where do I need to copy plgx(on linux)? I am testing it on my local system. When KeePassX-2 get installed, I can't see /usr/lib/keepass(x) but there is a .so inside /usr/lib/i386.../keepassx/ I tried copying there, but didn't work. I think we need to extend from this repos https://github.com/keithbennett/keepassx which has got keepasshttp working with previous Alpha version. 
I am new in OpenSource arena and QT as well, I'll try to understand how they are adding Keepasshttp support, I could get clue from there. Again there is a question, how can we make pull request to add this to Keepassx repos because I think I have to fork keepassx and then have to merge Keepasshttp, KeePassRPC(if required) features on top of it, followed by bug fixing if any and finally pull request?

Need your valuable input..

**Comment by dlech** [comment]
KeePass RPC is written in C# (using .NET framework) for KeePass 2.x. KeePassX2 is written in C++ (using Qt framework). There are two very different programs and frameworks. You would have to patch KeePassX2 the same way that kiethbennett did and basically rewrite KeePassRPC in C++ in a way the works with KeePassX2. Not a trivial task, but certainly doable if you are willing to put in enough time.

**Comment by luckyrat** [comment]
If you want to write something to communicate with KeeFox, you'll need to port KeePassRPC (at least the protocol, if not the GUI). Depending on the libraries available in your language, it could be fairly straight forward but if you've got to write your own JSON-RPC, websocket and crypto implementations it could get complicated quickly, not to mention much more risky. Documentation can be found here: https://github.com/luckyrat/KeeFox/wiki/en-|-Technical-|-KeePassRPC-detail

If you've got any questions regarding that, please open a separate issue.
