### ISSUE TITLE
Multiple logins and popup windows

### ISSUE THREAD

**Issue by skibbipl** [luckyrat/KeeFox#509]
Hello,
For some pages I have multiple logins. Unfortunately there is a not an easy way to select logins when login form is on popup window because keefox button is missing. Here is an example:
![disqus](https://cloud.githubusercontent.com/assets/4746858/8716758/995d42ca-2b94-11e5-8920-427f20d4264e.png)
And this is normal keefox button position:
![keefox](https://cloud.githubusercontent.com/assets/4746858/8716794/c7a1471c-2b94-11e5-96ff-c6bf095eb49c.png)
Under right mouse button I can see option find matching logins - but it populates only first matched login. Would it be possible to make this option aware of multiple logins?

I'm using latest keefox beta.

**Comment by luckyrat** [comment]
> because keefox button is missing

That is unfortunately the expected behaviour because Mozilla have decided to not support the Firefox improvements required to allow the KeeFox button to be included in these types of windows.

> Under right mouse button I can see option find matching logins - but it populates only first matched login. Would it be possible to make this option aware of multiple logins?

I have just tried it myself and the context menu is working as expected - I can see multiple logins under the "Matched login entries" submenu on the right-click menu.

Note that it is not possible to see this option from right clicking within a form field itself because this could lead people to expect the login to be filled into that exact form which has never been possible (obviously that's less of an issue on a page with a single form but that's not always the case so we have to be defensive). A new feature to enable that behaviour is tracked in #204.

**Comment by skibbipl** [comment]
OK, I just realized that my login details weren't correctly updated in Keefox (I was lastpass user and imported passwords from it). So I updated logins and now I can see them in the right click menu but they are displayed incorrectly - one login in submenu and another not:
![logins](https://cloud.githubusercontent.com/assets/4746858/8718068/3edc25d4-2ba1-11e5-9af7-8a7d52200f39.png)

**Comment by luckyrat** [comment]
That's correct. The submenu only appears for the 2nd and subsequent login items so you have quick access to the top result at all times.

**Comment by skibbipl** [comment]
Thanks for explanation!
