### ISSUE TITLE
Keefox 1.5.3b1 does not find username or password on https://mygoodtogo.com intermittently

### ISSUE THREAD

**Issue by contre** [luckyrat/KeeFox#510]
Using the latest beta as of today, keefox does not seem to be able to find the username and password fields on https://mygoodtogo.com/ about 50-60% of the time.

I created a new login using the 1.5.3b1 version using the old login info thinking there might have been an issue with having originally created the login using the latest released version instead of the beta.

Logs at debug level can be found at http://contre.us/keefox/log_failed.txt  http://contre.us/keefox/log_worked.txt

**Comment by luckyrat** [comment]
Please try [1.5.3b2](https://github.com/luckyrat/KeeFox/releases/tag/v1.5.3b2).

It fixes the problem with that website on my machine but it's a quick fix for a complicated bug so might need some more testing and refinement before it can be said to definitely fix the underlying problem (especially since it's intermittent for you).

**Comment by contre** [comment]
I have finally gotten around to testing with the that beta and was unable to reproduce the intermittent issue. Thanks so much for fixing this
