### ISSUE TITLE
KeeFox 1.5+ is not compatible with Pale Moon

### ISSUE THREAD

**Issue by TheLoneWolfling** [luckyrat/KeeFox#514]
I've always loved KeeFox. I'd love to use KeeFox 1.5+ and keep things up to date. Unfortunately, I cannot use versions after 1.4.8 due to them being incompatible with Pale Moon. And as time goes on I worry more and more about the security implications of using an out-of-date version (especially of a password manager!)

Am I SOL (and as such I should look at abandoning this addon and finding something that at least attempts to maintain compatibility / support for Pale Moon), or is this an oversight (and as such, something that will be corrected)?

I'm using Pale Moon 25.6.0 (x64) and KeeFox 1.4.8.

**Comment by luckyrat** [comment]
I know only a little about Pale Moon and have never officially supported it but as far as I know, it intentionally avoids including the modern web browser features that get included in new versions of Firefox, features that KeeFox 1.5 now requires (in order to allow KeeFox to keep working with the new versions of Firefox being released around the end of this year). So unless Pale moon changes that policy it is unlikely that KeeFox will work since I'm essentially left with a choice of supporting Firefox or Pale Moon but not both.

**Comment by luckyrat** [comment]
Let us know if anything changes in the world of Palemoon but as it stands now I don't see there is anything we can do here.
