### ISSUE TITLE
forms KeeFox does not fill

### ISSUE THREAD

**Issue by raven428** [luckyrat/KeeFox#532]
KeeFox does not fill [this](http://74.ru/passport/login.php) form even it previously filled by hand and saved to KeePass by KeeFox.

KeeFox unable to detect logins list and does not fill form with password selected by hand for vsphere6. [Here](https://cloud.mail.ru/public/MXRX/8UgwBj8cU) is example login screen of vSphere 6.0. KeeFox also unable to handle password save if this form filled and submitted by hand.

**Comment by luckyrat** [comment]
1) Works for me.

2) I don't see a login form on that page.

Are you using the latest KeeFox beta version?

**Comment by raven428** [comment]
This was version 1.4.8.1-signed. tried 1.5.3b10 and both works fine. Thank you, sir!

Is it possible to fill login/password forms in adobe flash appliactions from KeeFox?

**Comment by luckyrat** [comment]
I'm glad to hear it works.

It's not possible to fill in to plugins like Flash or Java from KeeFox, although you should find that the KeePass AutoType feature will allow you to automate it. Or with KeeFox 1.5 you could use the new copy username/copy password feature to manually paste the details into the Flash login form. If you don't use the site that often, I'd just go for the copy/paste approach but otherwise you might want to invest some time in getting an automated login working. http://keepass.info will have links to the docs and support you need to get started with the AutoType feature. It's not quite as intuitive as KeeFox but it's very powerful and is mostly understandable if you invest enough time with it.
