### ISSUE TITLE
Make option for less frequent "login to your database" notifications

### ISSUE THREAD

**Issue by mxt3** [luckyrat/KeeFox#533]
Currently, Keefox 1.4.8.1 shows on top of every page a notification when your not logged in into your KeePass database. My database locks up for example after waking from sleep, so I'm regularly confronted with this message, even when I know I won't need my KeePass database during a browser session. Plus the animation of this notification is a bit choppy, and it displaces the entire page after a small delay. Otherwise great extension,  no doubt the most useful I have!

**Comment by luckyrat** [comment]
Glad you're finding it useful.

Please try v1.5: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/1.5.3 

Not much we can do about the choppy animation - it's just the same built-in animation that Firefox has done since version 3 so that might indicate that your computer is struggling to meet the minimum requirements of Firefox. Either way, we don't use that particular feature any more in KeeFox 1.5 but you might still find some of the other standard Firefox animations are a bit choppy.
