### ISSUE TITLE
Keefor 1.5.3 is annoying

### ISSUE THREAD

**Issue by borys-p** [luckyrat/KeeFox#537]
Hi,

Keefox is asking me to save credentials after submitting forms not even remotely resembling username or password. I save a form with "name" field at the beginning - popup appears. I click `<button>` which fires jquery callback - popup. It happened before, but with this new big popups it has got really annoying.

Keefox is great, but sometimes too aggressive.

**Comment by luckyrat** [comment]
Hi,

> not even remotely resembling username

In my experience, `name` often resembles a username field but I'm always happy to hear of other opinions and experiences so thanks for the feedback.

You can change this behaviour by adding a [site-specific setting](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options#keefox-per-site-options-dialog) for the particular website you're seeing a problem with. Create a new site entry for the relevant URL and modify the `Text field name` whitelist.

Depending on the contents of the rest of the form in question, just removing `name` from the whitelist might be enough but if not, stick it into the blacklist.

In fact, you could make this same change on the global (*) site-specific configuration entry but I suspect if you take that approach you'll gradually notice that more sites use `name` as a username field than you think.

Any idea how common this problem is for you? Is it just one or two websites? Is it always the `name` form field that triggers the problem?

The list of whitelist and blacklist entries is primarily based on my personal experience and the occasional bit of feedback about specific sites over the past 10 years but site structures change over time and if we start getting a lot of reports about a particular whitelist or blacklist entry being unsuitable for the default list we can change the defaults in a future KeeFox version.

**Comment by borys-p** [comment]
Hi,

Thanks for quick answer!

Unfortunately most forms that I'm using have the "name" field, as it's very common (person name, item name, other record name, etc.). I tried white- and blacklisting those fields, but AFAIR it didn't work too well.

Maybe you should consider not capturing the most common field names (like "name"), when there's no password field in the same form? It would disable most of these false alarms. 

Or maybe Keefox should be able to "learn" to ignore certain forms? You'd only have to click "ignore form" once. Quite like with NoScript, you have to whitelist a lot of sites in the beginning, but then it's very unobtrusive.

And it's still a mystery to me why Keefox is being triggered by clicking a <button>. For example I have created a form to add an offer. It has a "name" field and a Google map, where you can drag the marker to your offer position. There is also a <button> which triggers the decoding of entered address to map coordinates and returns false. Seems like Keefox it ignoring this returned value and thinking that the form is being submitted. Is it some hack for poorly-written ajax forms? And is there any way to tell Keefox "ignore this button"?

**Comment by luckyrat** [comment]
> It would disable most of these false alarms.

Unfortunately it also disables many legitimate login forms where the password field is not present until the username has been filled in.

> Or maybe Keefox should be able to "learn" to ignore certain forms? You'd only have to click "ignore form" once. Quite like with NoScript, you have to whitelist a lot of sites in the beginning, but then it's very unobtrusive.

That's possible but might be too much work for me to consider in the foreseeable future and risks confusing less technical users, especially when sites start changing their form structures as they tend to do over the years.

#444, #448 and #259 are very related to this idea.

> And it's still a mystery to me why Keefox is being triggered by clicking a `<button>`.

If the button is attached to a form (either implicitly or explicitly) KeeFox has to assume that a click on it is equivalent to a form submit event. KeeFox must make this decision before any website script has executed so we can't even consider the benefit of inferring intention from the actual script execution result.

The issues listed above should between them offer a way to at least approximate an "ignore this button" feature but it's going to take a fair amount of work that I can't commit to until Mozilla's future addon strategy is more definitively going to allow powerful addons like KeeFox to exist for at least 5-10 years (right now we're in a "probably OK for 18 months state" which is insufficient for me to commit time to non-trivial new features).

**Comment by borys-p** [comment]
> Unfortunately it also disables many legitimate login forms where the password field is not present until the username has been filled in.

I have never used a website that does it other than banking sites... I could safely disable this option. Even better would be to have an option to "start watching all forms" which would make keefox more aggressive. Now it's too aggressive all the time.

> That's possible but might be too much work for me to consider in the foreseeable future and risks confusing less technical users, especially when sites start changing their form structures as they tend to do over the years.

This is type of advanced option that should be disabled by default. #259 "Never for this site" + keepass entry for this site with exact match login URL would disable all false positives.

As for now I'll experiment with blacklisting certain forms. But probably I'm not the last person that will open similiar ticket :)

**Comment by luckyrat** [comment]
Closing since there are already tickets to cover some specific improvements from this discussion and the overall issue is too broad to address.
