### ISSUE TITLE
Selection of entries in htaccess Auth seems broken (1.5.3)

### ISSUE THREAD

**Issue by atomtigerzoo** [luckyrat/KeeFox#542]
With version 1.5.3 it seems there is a problem with the selection of matching entries when trying logging into htaccess auth protected locations.

**Before & suspected behaviour:** correct listing of entries from KeePass matching the URL from the URL field

**Current behaviour:** lists all entries from a group having the URL as name, lists entries where I cannot make any connection why they are listed (from trash, entries without url and nothing matching, etc). Lists a lot (~40-50) entries (before and correct mathing: only 4)

**Comment by luckyrat** [comment]
Are you sure they are from trash and without URLs? I don't see that behaviour.

As described in https://github.com/luckyrat/KeeFox/wiki/en-%7C-Upgrading-from-KeeFox-1.4#a-different-http-auth-login-is-being-filled-in-than-before it's not unexpected that some combinations of password entries would result in more matched entries and a different ordering. I would expect that they at least belong to the same domain though so your description sounds like there might be a bug in some cases so it would be good to dig a bit deeper in case there is something we can change in the next version.

**Comment by berndwaibel** [comment]
I have the same problem. When the dialog "Authorization required" (or "Authentifizierung erforderlich" in german) opens, a lot of entries are shown. Before the update, I got 2 or 3 possible entries, all correct. Now I have lot (50 or so) of entries. Currently I could not find out what matched. Screenshot (the grey box is hiding my names):
![unbenannt](https://cloud.githubusercontent.com/assets/10959449/9898295/6581f778-5c51-11e5-8ada-c40f2275db60.png)

**Comment by berndwaibel** [comment]
Ok. I do not find out matching values in the entries. For example there is a user "shopadmin", which is used for some very different login, and does not have some matching criteria for the web page. It seems that "all" entries are listed.

The shown enries are always constructed with the pattern "username - hostname.mydomain.de"..
All entries have or do not have a "username", the "-" sign, and the same hostname as the selected page. But this hostname does not been extracted from the keypass entries.

For example:
I open the page "nagios.mydomain.com". The http autorization is shown, the list of selected entries contain: 
* admin - nagios.mydomain.com
* shopadmin - nagios.mydomain.com
*  - nagios.mydomain.com
* - nagios.mydomain.com
* admin1 - nagios.mydomain.com

and so on. So there are entries without a username. And the hostname is always the hostname of the opened page, not the hostname of the group or the url inside keypass.

It seems to me, that the matcher does select all entries, but does pre-set the hostname with the searched hostname and not with the hostname from keypass.

**Comment by luckyrat** [comment]
Do the matched entries have a HTTP Realm defined on the KeeFox tab in KeePass' Edit Entry view?

If so, is it always the same?

Do any of the entries have KeeFox priorities set?

**Comment by berndwaibel** [comment]
I looked inside Keepass, opened the "shopadmin" entry in Edit mode, and opened the Tab "Keefox".
The "General" Tab has: 
* Hide this entry from Keefox: not selected
* Priority override: emtpy
* HTTP Auth Realm: empty
The "URLs" Tab has:
* Domain: The URL only needs to be part of the same domain to match.
Btw.: I never used this properties before. So they should not be set anywhere, so this may be the default.

When I change the "Minimal URL match accuracy" to "Hostname" instead of "Domain", the entry "shopadmin" will not been shown in the list again. So this may solve the problem.

But: How do I change all entries in my database? 
Even the entries without username, how should I find out which one is used?
Is "Domain" the default? Is this a good decision using the domain as default for an entry?

Is the "Minimal URL match accuracy" a new feature? 
I never have seen this before (but I never searched for ;-) ).

**Comment by berndwaibel** [comment]
Solution (as hint for user which opened this issue):
 
Update the "Minimal URL match accuracy" of your entries inside KeePass on the KeeFox properties page, on the "URLs" tab. Select "Hostname" or "Exact" instead "Domain".

Just as solution hint.

**Comment by berndwaibel** [comment]
Feature Request:
The listed entries do use the hostname of the opened page (which is always the same).
It would be better to use the hostname from the KeyPass URL.

**Comment by atomtigerzoo** [comment]
So, do I get this right, when the matching selects parts of the domain (the htaccess is on a subdomain) and that is why I see all entries matching the TLD?

The hint or solution is that easy, because I have a lot of entries for the main TLD :/ 

I would favour the feature request of @berndwaibel to change the default matching to the full hostname - or even URL - and to let the user change it to a wider matching.

**Comment by berndwaibel** [comment]
Workaround for updating all entries:
It should be possible to correct all entries in a KeePass database by using XML.

The "Minimal URL match accuracy" is stored inside the "KPRPC JSON" Property. 
Right?

Two possible solutions:
1. Use XPath (Tools -> Database Tools -> XML Replace). To complicated for me.
2. Export DB (File -> Export -> Keepass XML 2.0), make changes using any editor, Re-Import DB in a new DB.

Possible values of the KeeFox selections:
* Domain: "blockHostnameOnlyMatch":false,"blockDomainOnlyMatch":false
* Hostname: "blockHostnameOnlyMatch":false,"blockDomainOnlyMatch":true
* Exact: "blockHostnameOnlyMatch":true,"blockDomainOnlyMatch":false
Right?

So search-and-replace of this string should work.
Just an idea, not tested now. Try on your own risk.

**Comment by atomtigerzoo** [comment]
But a search-replace in the raw-database cannot be the solution :/ It seems like the new default setting is the problem - maybe it can be reverted? Or set/choose it globally?

**Comment by luckyrat** [comment]
The "Tools -> Database tools -> XML Replace" feature is the solution. Thanks @berndwaibel for pointing me to it - I hadn't noticed this feature was added to KeePass in version 2.25.

The examples below should get you started but you'll have to think about which is most appropriate for you and maybe do some prep work first (e.g. move affected entries into a specific KeePass group or a seperate database).

As you will see, it's possible to change the setting for every entry but this would be bad for any "normal" website logins so you should only apply the change to all entries if you know you are working with a database that is primarily used to store a large number of customer logins. You should keep your everyday personal passwords set to the default "Domain" match behaviour.

Also note that this has only been tested on a small database containing no vital passwords so caveat emptor - take backups!

You can preview the changes made before saving the database by opening some of your entries in KeePass but you will have to save the database before KeeFox will see the changes (hence the requirement for a backup or two, although KeePass should record history entries for each change so even the worst case scenario should be recoverable with enough work).

First ensure the Action is `"Replace data"` and the Data is `"Inner text"`. Then set:
Find what: `"blockDomainOnlyMatch":false`
Replace with: `"blockDomainOnlyMatch":true`

"Select nodes" is the most complicated bit so build up your own XPath using the following examples as a guide:

All entries in the database (not recommended):
`//Entry/String[Key='KPRPC JSON']/Value`

All entries within the "A group name" group or any of its subgroups:
`//Group[Name='A group name']//Entry/String[Key='KPRPC JSON']/Value`

All entries with a URL that contains 'reddit.com':
`//Entry[String[Key='URL' and contains(Value,'reddit.com')]]/String[Key='KPRPC JSON']/Value`

Let me know how you get on.

By the way, you should not export your database to XML and manually manipulate the file because all of your passwords will then be stored in an unprotected format for a period of time.

**Comment by berndwaibel** [comment]
Nice work!!

**Comment by atomtigerzoo** [comment]
Thanks for the explanation, but I have to say this is not very user friendly. With a large database I am not very happy to split it, change it in any way (because it was working flawless) just because of a new default setting. (No offense)

What was the reason to change this default behaviour and what is the advantage? I cannot see any :/

Is there no possible way to revert or check something to keep things the way they were?

**Comment by Electrofenster** [comment]
I go back to 1.4.8 without the "ugly-"new-popup and the annoying "feature".
I think @luckyrat should make a new release with a feature to disable the new annoying "feature"

**Comment by atomtigerzoo** [comment]
I have to say I am going back too to 1.4.8. I don't have the time to edit all the entries for multiple htaccess sites, also all my Piwik logins stopped working and I have issues with the nag-screen to update my entries. Only good: the trello and twitter login were filled. But that's not worth it. Sorry to say this, but this version is not for me.

**Comment by Electrofenster** [comment]
Yep, you're right. That Version is not helpfull, it makes a lot of work to edit all the entries. I't stopped working on multipile sites and I've more entrys for some sites as with the version 1.4.8.

**Comment by luckyrat** [comment]
> I have to say this is not very user friendly.

I agree. There is no time to make this user friendly; perhaps if these problems were raised at an earlier stage of the beta testing process we could have addressed them in a more user-friendly way but even then, you must understand that the primary reason for this release of KeeFox is to make it work in the new versions of Firefox so tasks that would have potentially delayed the release might still have been impossible to achieve in time.

> What was the reason to change this default behaviour and what is the advantage?

This is explained in the release announcement on the official website. Essentially it is a far better behaviour for at least 99% of KeeFox users. The disadvantage of more cluttered lists of matched logins for a small number of users until they reconfigure their database is far outweighed by the advantage of easier initial configuration and getting much closer to "it just works" for new and typical users.

Those of us that are adversely affected by this change should be in a far better place to understand the technical issues and resolve them than the majority of people that are simply enjoying the improved behaviour.

> I go back to 1.4.8

Of course you should do this if you're unable to work with the new version but this can only be a temporary solution (and in fact is already not an option for users of Firefox 42) so I urge you to only postpone addressing this issue rather than ignoring it and hoping it will go away eventually.

> make a new release with a feature to disable the new annoying "feature"

There is no chance that I'll disable the new feature, for the reasons explained above. Offering an option to disable it is not out of the question although I am not yet convinced it is a good idea and I am also unsure if such an option could even be possible. Either way, there will be no instant change to this feature and I can make no promises that there will be any change before 1.4.8.1 stops working with a new Firefox version, hence my earlier post explaining the pragmatic, albeit non-user-friendly, solution to this problem.

**Comment by kitesurfer377** [comment]
>>make a new release with a feature to disable the new annoying "feature"

>There is no chance that I'll disable the new feature, for the reasons explained above. Offering an option to disable it is not out of the question although I am not yet convinced it is a good idea and I am also unsure if such an option could even be possible. Either way, there will be no instant change to this feature and I can make no promises that there will be any change before 1.4.8.1 stops working with a new Firefox version, hence my earlier post explaining the pragmatic, albeit non-user-friendly, solution to this problem.

But what is about a panel to in the options menu, where users can set a default-value for new entries,
based on this information:
>Domain: "blockHostnameOnlyMatch":false,"blockDomainOnlyMatch":false
Hostname: "blockHostnameOnlyMatch":false,"blockDomainOnlyMatch":true
Exact: "blockHostnameOnlyMatch":true,"blockDomainOnlyMatch":false

For excample like this:
blockHostnameOnlyMatch: yes || no
blockDomainOnlyMatch: yes || no

Like this, people are able to choose the default URL match accuracy for new entries

**Comment by luckyrat** [comment]
> But what is about a panel to in the options menu

I'm not sure this will be possible, but it's definitely not trivial, adds complexity for less technical users and adds another thing to potentially confuse debugging so I can't justify spending any time on it unless long-term usage of the new domain matching proves problematic.

> Like this, people are able to choose the default URL match accuracy for new entries

New HTTP Auth entries default to the more precise matching of previous KeeFox versions but it is not possible to determine which existing entries are used only for HTTP Auth so we are conservative during the upgrade process, leading to it being more likely that we match too many entries than not enough (partly based on the assumption that the handful of people with so many entries to make this a problem are more likely to be technical enough to search out a way to reduce the number of matches compared to the majority of users with a few passwords where some entries failing to appear at all could be a show-stopping problem).

**Comment by david-jezek** [comment]
I understand that you are focusing 99% of KeeFox users. But ther is another problem connencted with URL matching. I change my database and url matching rules acording new behavior. KeeFox corectlly find and fill login to web page, but after login always popup big ugly dialog to save new password. But thers is no new password, kee pass already known the password and corectly fill it in.

**Comment by luckyrat** [comment]
@david-jezek that does not appear to be related to this issue. Please search the manual, support forum and other issues for help and post a new issue if you can't find a solution to your problem.

http://keefox.org/help

**Comment by berndwaibel** [comment]
Tried around some things, but I did not get happy.

You changed the behavior from one version to another. Thats it. It is not "keeping things run", it is a changed behaviour. Does not have to do with Firefox release. Before the update, the keefox for http auth was matching the url, now it is matching the domain. 

As you stated: "This is explained in the release announcement on the official website. Essentially it is a far better behaviour for at least 99% of KeeFox users." I did not find this in the release notes, and i did not get why this is "far better". It is like google: Search for documents containing "A and B", and you get all documents containing "A" and all documents containing "B". Not "A AND B". Sure, getting all entries in the password list makes sure there is an entry. But questions is: do i really need all entries, or the one-and-only matching one.

I am domain admin, so guess how many of my about 200 URLs start with the same domain...

I tried to change the KPRPC JSON. But that does not work. The JSON does not exist in all entries. If it does not exist, or on every new entry, it is just "match domain" (the default we are all talking about). If it is default, there is no "JSON". So every entry without "JSON" will match. Every new entry will match. Everything will match. Everything. Why should a new created entry match all http auth logins in the same domain?

I know that I am talking about free software, open source, and so one. I appreciate your work, it is hard work, and it is one of the finest tools I know. It works fine for everything. Except http auth.
I do not have a solution.

**Comment by Electrofenster** [comment]
Maybe he can provide the old version without the automatic update function?

**Comment by atomtigerzoo** [comment]
It's me again ;)
I made the update to the new version because I need the login at trello (which only works with the new version). There are quite a few things abroad this issue which bother me too, and I see that they are all 'won't fix' in other requests. This is sad to see.

But I really have a problem with this very loose matching of only the domain. See, there are sites like ebay which offer different services under subdomains: www.ebay.de and kleinanzeigen.ebay.de for example. The new version now lists all logins for both. Same goes for other sites that use different logins (ie. blog-networks, multisites, developement of client stuff under subdomain and so on). Why can't the default behaviour not be that it will match the whole domain aa.bb.cc? Every new entry - and this means every new user - will save the correct URL to the database. So no problem there. Only problem is with old users converting to the new version.

I really don't want to stress this issue. But it bothers me. It bothers many others. And I really don't know if it is so useful in the end to have such a broad matching.

All in all: what must happen that the development would speed up again, that requests like these (change the domain matching/add a option for this) would get through - and also other request could get more attention or work?

**Comment by berndwaibel** [comment]
I reworked my database. Changed every entry, more than 200 entries. Cleaned up the entries and deleted some old ones. Took some hours work.

* checked "hide this entry from KeeFox" to all rdp://, vm://, ssh://, and so on URLs.
* Set "hostname" to all "http://", "https://" urls (some to exact match) in my domain
* ignored every other domain (the most urls share one domain, did not bother about the rest www).

So I "fixed" my database to match the new behavior.

Btw. I do not only use "http" URLs.

**Comment by luckyrat** [comment]
@atomtigerzoo RE development speed in case you've not seen my recent update: http://keefox.org/news/detail/2015/10/18/keefox-in-2016-and-beyond

@Electrofenster: 
> Maybe he can provide the old version without the automatic update function?

Old versions will stop working with Firefox 44 (earlier if you're on the beta or developer edition of Firefox) and anyway, auto update is controlled by Firefox so you can change that for a few weeks if you want but you're only postponing the issue.

@berndwaibel:
> i did not get why this is "far better"

Most users don't understand domains, hostnames and URLs. They also do not understand why the "website" they are on does not auto-login when they access a different section of the site or load the new login page (which happen to be on a different subdomain). This change makes KeeFox's behaviour match more closely with a normal user's understanding of a website's boundary. Another big benefit is that these new boundaries are also matched by the security boundaries of Firefox with respect to cookies, per-site configuration and permissions, etc. which significantly reduces the risk of users misunderstanding security boundaries and making mistakes that compromise their security or privacy. I could go on about benefits for "normal users" but...

Of course there will be exceptional users...

> I am domain admin

... like that.

I made sure the behaviour is configurable. I'm sorry that there was not time to develop more options and more migration tools but as you've found, a few hours work can resolve the issue (in what is probably a worse-case situation) vs many days of my time for an issue that beta testing indicated zero people would benefit from. It's unfortunate for you and the few others who need to spend some significant time manually adjusting entries but that still compares favourably with the option of undertaking lots of extra development work despite no evidence of need.

> Btw. I do not only use "http" URLs. I use "URL overrides" to start e.g. putty with "ssh://" URLs. They need to have "ignore" to KeeFox, to get rid of them in the http auth list.

Interesting. This is the first I've heard of that behaviour but I guess it makes sense because of our need to support file,pop,imap,etc. I'm not sure we can do anything about that but perhaps we could come up with a white (or black) list to manage it better in future.

> And the hostname is always the hostname of the opened page, not the hostname of the group or the url inside keypass

This is because we don't know which URL was matched in KeePass (just that it matched and how good a match it was). However, in the majority of cases we can make a good guess that it is the first (only?) URL associated with the entry so I think it's worth improving this behaviour if we can.

It also appears that we don't correctly order the entries listed in the HTTP Auth dropdown box so that's a bug that when fixed will at least make it reasonable for you to assume that the items at the top of the list are the one's you're most likely to be interested in on that page even if you've not yet modified the KeePass entries to enable more accurate matching on that domain.

**Comment by luckyrat** [comment]
See #568 and #569

**Comment by luckyrat** [comment]
The related issues spawned from this discussion have been implemented and I don't see any further actionable tasks in here so I'm closing this one.
