### ISSUE TITLE
Can you provide DLLs for KeePassRPC.plgx for KeeFox 1.5.3?

### ISSUE THREAD

**Issue by pokedroid** [luckyrat/KeeFox#543]
PLGX files doesn't work on my Debian machine. Only DLLs work.
I happened to have KeePassRPC dlls from 1.4.4.0 (don't remember how I got them), so I'm stuck with KeeFox 1.4.8 for now.

Thanks

**Comment by dlech** [comment]
.plgx files should work just fine in Debian unless you have mono 3.0.x for some reason. You can check by running `mono --version`.

If you don't have mono 3.0.x and it still fails, it is generally because you don't have the mono compiler installed. `sudo apt-get install mono-complete` will take care of this.
