### ISSUE TITLE
about:config entries remain after Keefox is removed

### ISSUE THREAD

**Issue by williamtheaker** [luckyrat/KeeFox#572]
I removed KeeFox a while ago, but I still have about:config entries like extensions.fams@chris.tomlinson.installTime.KeeFox

Using Iceweasel/40.0 on Debian

**Comment by luckyrat** [comment]
Yeah that's just how Firefox works. It's impossible for addons to clean-up after themselves (even if it were a good idea). In this case it probably is not a good idea because the annoyance of losing all settings after a temporary uninstallation is huge compared to the small annoyance of a few KBs of extra disk space being used for eternity.
