### ISSUE TITLE
KeeFox saves the first tried password

### ISSUE THREAD

**Issue by DiamondKing099** [luckyrat/KeeFox#579]
When I sign in to a website and I get the password wrong on the first time, but then get it correct on the second or third time, and then click the "Create Entry" button on the KeeFox popup, it saves the first (incorrect) password, so then I have to open up KeePass and edit the password manually.

This is only a minor annoyance, but if this issue could be addressed that would be good. Thanks!

**Comment by luckyrat** [comment]
KeeFox can't know whether the password was correct or not. Only you know that.

Therefore (as explained in the tutorial) in order to prevent KeeFox from interpreting the login as a multi-step login procedure you should dismiss the save password panel if you make a mistake.

(If you look at the KeePass entries that were saved, the correct details will be saved, but just on page 2 or 3 of the login process).
