### ISSUE TITLE
Save Entry Dialog off Screen

### ISSUE THREAD

**Issue by Ratief** [luckyrat/KeeFox#581]
Today I finally realized why I haven't seen any save entry dialogs for a very long time. If you don't have the KeeFox icon on a toolbar (because there is no reason to have it taking up space), then the save entry dialog shows up below the entire Firefox window (which for me makes it show up off screen). Once I added the KeeFox icon back to a toolbar everything started showing up again as the popup chat style bubble.

So there needs to be a check that if the icon isn't being displayed, then the dialogs should popup somewhere that *IS* visible. Maybe the top of the current tab like they use to?

**Comment by luckyrat** [comment]
There might be something we can do to fix this - depends on if it's a KeeFox issue or Firefox bug but I don't have time to investigate at the moment.

**Comment by luckyrat** [comment]
I can't replicate this problem. In FF44+ at least, Firefox displays the "Save entry" popup anchored to the "main menu hamburger" when I have KeeFox in there instead of on a toolbar.

As far as I know, this behaviour is fully under Firefox's control so it's odd that it doesn't work on your Firefox. Do you have any other addons installed?

What happens when you invoke the KeeFox main menu by pressing Ctrl+Shift+1? For me, it automatically opens the main menu panel and displays KeeFox as expected.

**Comment by Ratief** [comment]
I think I have an idea of why it is happening. I use the add-on "Classic Theme Restorer". So I don't have the new style menu, but the older style in the title bar (I like having a title bar with the current page title). So I'm guessing that it tries to make the popup appear from the toolbar icon, then the menu icon. Since I don't have either it fails and the popup ends up showing up under the entire Firefox window (and off screen for me).

As for Ctrl+Shift+1, it opens the KeeFox panel, but only when I have the KeeFox icon on the toolbar.

It is an interesting find... but you probably shouldn't spend any more time to fix something that only effects one person. I'll probably just live with an unneeded icon on my toolbar.

**Comment by luckyrat** [comment]
Thanks for the information. It doesn't sound like something we could fix in KeeFox even if we had enough time so I'll close this issue.
