### ISSUE TITLE
How secure is it?

### ISSUE THREAD

**Issue by Marsfan** [luckyrat/KeeFox#597]
So I have been using this plugin. It seems great, but how can I confirm that it is secure. Could someone point me to a 3rd party source that confirms this?

**Comment by luckyrat** [comment]
I'm not aware of any official security reviews but the wiki has lots of technical information describing how secure it is and the implementation is open for all to see. As you'll see from the wiki, while there are a few novel approaches, the key building blocks of both KeeFox and KeePass are independent 3rd party secure implementations (e.g. Firefox/NSS and .NET crypto primitives) which significantly reduces the risk of implementation problems and means that the customised protocols are simpler to analyse. I know other people have reviewed the protocols and implementation and were satisfied but it's another matter entirely to put ones name to an official statement of security.

I'm closing this issue since it's not directly actionable (and open issues here don't tend to attract 3rd party attention any more than closed ones) but if you do find any 3rd party confirmation, I'd be interested to see some new comments here.
