### ISSUE TITLE
[Feature Request] support multiaccount for google

### ISSUE THREAD

**Issue by F43nd1r** [luckyrat/KeeFox#606]
When I log in to one of my google accounts, I first select one of my usernames, then google asks for the password. KeeFox always uses the standard password and overwrites my username selection. I'd like to have KeeFox honor that username selection instead of overwriting it.

**Comment by luckyrat** [comment]
A multi-page login should do the job if it really bothers you but to be honest I don't remember the last time I saw google ask me for a username - it just presents a set of buttons to click on for each account and then moves onto to the password page once I've told it which username I want to log in using. Selecting the appropriate user through KeeFox fills the correct password for the correct account.

In theory we could work out which username button you clicked on within the Google page and then force KeeFox to prioritise that username when the next page loads but I won't implement anything like that in practice because it will take a lot of work for just one website and add complexity and fragility to KeeFox for a barely noticeable improvement. Given that it can take months for new versions of KeeFox to get approved by Mozilla, any features that can be broken by 3rd party websites are a massive risk so the benefit needs to be much larger than saving a mouse click a few times a day.
