### ISSUE TITLE
Using KeeFox in multiple browser instances. (e.g. Firefox and Tor-Browser-Bundle)

### ISSUE THREAD

**Issue by henningsway** [luckyrat/KeeFox#610]
Dear Chris,

first of all thank you for your work on the addon, it work's really well and prooves superuseful!

I recently started to use the Tor-Browser-Bundle a little more and it would be very convenient, if I could set up _KeeFox to work for both Tor and Firefox at the same time_.

I use Linux (Ubuntu) OS on my computer and and Keepass and KeeFox for Firefox is already set up. Now I don't know how to proceed and it seems I would have to replace the plugin for Firefox if I want to install the plugin for Tor-Browser.

I found this note in the Wiki https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options-%7C-KPRPC-Port and it seems to be helpful. But I'm not sure, in what way I would have to modify my config file, where I would find it and if KeeFox for Firefox will still run after the tweak.

Any suggestions welcome. Is this the right track?
Kind regards

**Comment by henningway** [comment]
Hmm... other issues have been answered already. Is the answer that obvious or is it not as simple as it might seem?

A short comment would be very much appreciated. Thank you! :)

**Comment by luckyrat** [comment]
I don't know. I have heard conflicting reports as to the compatibility of Tor with KeeFox and have no experience of it personally.

I'd recommend using KeeFox 1.6 if you're going to try using custom ports (which you're correct in thinking would be required if you want to run more than one browser at the same time).

https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta

**Comment by winter20161** [comment]
Hi, i got the same problem as hennigsway, and i fixed it. Although my os is windows, not Ubuntu. I think i might also be useful for Ubuntu, or perhaps for all os'. Since Tor Browser routes all traffics, using proxy settings, to 127.0.0.1:9050 or 9150, and keefox communicates with KeePass via port 12546 (default). All you have to do is to **add an exception in Tor Browser's proxy option**.

Method: Tor Browser > Options > Advanced > Network > Settings
**Add an entry in the "no proxy for:" 127.0.0.1:12546** (replace "12546" with your keepass listening port, if you ever changed it.)

After this, Keefox works fine both on my Tor Browser and Firefox. I wish this method helps.

**Comment by henningsway** [comment]
this really works. Great, thank you. :)
