### ISSUE TITLE
Overloaded KeeFox menu popup

### ISSUE THREAD

**Issue by BoffinbraiN** [luckyrat/KeeFox#614]
When KeeFox displays a prompt (such as to save a login), pressing the toolbar button will show the prompt *and* the KeeFox menu in the same popup.

A minor issue, but can look a bit odd. Maybe clear any prompts before showing the menu?

![doublepurposepopup](https://cloud.githubusercontent.com/assets/13255058/12919750/6aa6ab40-cf3d-11e5-9113-e6932ae286b2.png)

**Comment by luckyrat** [comment]
The popups must be displayed in order to ensure that incidental, accidental or exploratory clicks do not discard information required for saving passwords (likewise for most other prompts).

**Comment by BoffinbraiN** [comment]
Would it be possible to do what Firefox does natively instead? That is, put an icon in the URL bar so that if the popup is dismissed, it can be opened again.

**Comment by luckyrat** [comment]
Probably yes, although the latest add-on design guidelines (Australis ~2 years ago) discourage that approach so I've intentionally chosen to not pursue it before. In fact, Mozilla seem to be going against that guidance with new built-in Firefox features so I no longer expect it to be a contentious issue. However, I won't be making substantial UI changes like this for at least a couple of years because the future of Firefox addons is still uncertain. If Mozilla commit to and implement addon infrastructure that enables KeeFox to survive, I'll assess what the best UI approach is at that time.
