### ISSUE TITLE
Can't install KeeFox on Firefox 44+ if .NET or KeePass setup is required

### ISSUE THREAD

**Issue by gennadykh** [luckyrat/KeeFox#633]
Was trying to install KeeFox but this page chrome://keefox/content/install.xul never loaded needed files.
What is a problem?
Why it is a chrome in the link?
Thank you

**Comment by dlech** [comment]
I am assuming you are using Windows. It is possible that antivirus or system configuration or something else has blocked the installation. You can always [install the KeePassRPC plugin in KeePass manually](https://github.com/luckyrat/KeeFox/wiki/en-|-Getting-started#manual-installation).

"chrome" is just an internal Firefox name for "the shiny stuff" - in other words, the user interface/what you see on the screen. In this case, it just means that the page you are looking at is an internal page of the KeeFox plugin and not a web page out on the Internet somewhere.

**Comment by luckyrat** [comment]
This is probably due to the changes made to const semantics in Firefox 44 - I missed the ones being used in the install scripts since they only cause a problem when an initial download happens rather than an upgrade from an earlier version. I have a fix I'm testing at the moment ready for the KeeFox 1.6 release.
