### ISSUE TITLE
Improving Firefox startup time with Keefox installed

### ISSUE THREAD

**Issue by Nocturnalizer** [luckyrat/KeeFox#635]
Hey :)

Do you think it's possible to optimise the startup time of Firefox with Keefox installed? I've noticed a slight delay in the browser launching, compared to not having the extension active. I run a modern system with an SSD, and while it's by no means dreadful, Keefox does have a bit of an impact on the time it takes for Firefox to fire up. We're talking maybe an extra second than it normally would. Any chance that could be improved? 

I'm currently using Firefox 45 x64, though have experienced the delay on 44 and on fresh installations etc.

Thanks for reading!

**Comment by luckyrat** [comment]
As far as I know, KeeFox already delays everything that it can during startup so I'm afraid the short answer is no.

Depending on what other extensions you have installed, it's possible that the extra time is not directly related to KeeFox but that it's presence causes Firefox to load a lot of features earlier than it otherwise would need to. In that case, we might expect some slight improvement from the Firefox side of things in future.

Since the future of addons like KeeFox is unclear while Mozilla redesign their add-on system over the next year or two, it's difficult to say that there will be no future improvements in startup speed but it's not something I will spend any time on directly unless a large performance drop is observed and there is a feasible fix offered by Firefox.

KeeFox 1.6 removes some legacy code from the add-on so there is a small chance this might speed up load times a bit but without dedicating a lot of time to investigating the specific causes of the slow startup on your system it is impossible to predict.

Sorry I can't offer anything more definitive but thanks for raising the issue - I've not noticed any such delays on my machines so it's helpful to know that this is happening to other people.
