### ISSUE TITLE
Http Auth broken in Firefox 47

### ISSUE THREAD

**Issue by Larusek** [luckyrat/KeeFox#637]
Hi
I recently noticed that http auth is not filling login data anymore. First I thought it was something with my entries but then I tried the Keefox Tutorial "KeeFox sample entry for HTTP authentication" entry and it didn't work either. 

http://i.imgur.com/1Y86YCb.png

Keefox 1.6.0b2
Firefox Nightly 

Could anyone confirm ?

**Comment by luckyrat** [comment]
Confirmed in Firefox 47 (including developer edition).

Looks like it fails on this line:

https://github.com/luckyrat/KeeFox/blob/43e2b3b7ba4c54301c11def0a7dc147bd8b46dbc/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L223

`if (Application.id == "{3550f703-e582-4d05-9a08-453d09bdfdc6}")`

That's there to enable Thunderbird-specific behaviour.

`Application` is part of the FUEL library which at one time Mozilla expected us to use when developing new add-on features but they have now deprecated it.

The last time I looked there was no alternative way to establish if we were running within Thunderbird or Firefox but hopefully the fact that Mozilla now appear to have broken all add-ons which use this feature is a strong indication that an alternative approach is possible.

However, according to the [Firefox 47 release notes](https://www.mozilla.org/en-US/firefox/47.0a2/auroranotes/): “FUEL (Firefox User Extension Library) has been removed, add-ons relying on it will stop working, use add-on SDK instead.“ - since KeeFox cannot use the add-on SDK instead, we may have hit a large problem.

**Comment by dlech** [comment]
Hmm... I wonder how hard it would be to split this into two addons (Keefox and Keebird) with most code shared? Thunderbird and Firefox are diverging, so Keefox in its current form will be compatible with Thunderbird for much longer than it will be compatible with Firefox. Just a though.

Also, I wonder if you can simply change this to 

    if (Application && Application.id == "{3550f703-e582-4d05-9a08-453d09bdfdc6}")

**Comment by luckyrat** [comment]
Any mention of Application causes Firefox to throw and swallow an exception - even debug log lines just never get hit.

I guess in the bigger picture, it's hard to see how KeeFox and KeeBird can continue being part of the same codebase if Thunderbird are not going to adopt WebExtensions since Mozilla are saying they'll force all add-ons to move away from XUL in the next couple of years. I've not seen any roadmap for Thunderbird recently but the general direction has been towards a split with the Firefox code-base so it makes sense that the two add-on ecosystems will eventually no longer be compatible - I just have no idea of the speed at which that would happen.

I've not had enough time to look into the latest situation regarding the sort of changes that will be needed to move KeeFox away from XUL but I hope there will still be a lot of code that is shareable with a XUL add-on for Thunderbird (and older Firefox forks?) since otherwise that means pretty-much a complete rewrite to retain Firefox support and I'll definitely not have time for that.

It's easy enough to see how we could fork into a separate KeeBird add-on but not so clear how it would be able to continue sharing code - to do so even in the short term would require a little planning.

Having seen a recent add-ons blog post talking about all the upcoming changes, I had already started to think that a KeeFox v2 might need to cut ties with a lot of the old codebase and abandon many features in order to continue working with newer Firefox versions - but I'm hoping that will be a fair way into the future so hopefully that's not our only possibility to resolve this FF47 problem.

I know that within a jsm, `Services.appinfo.name` (after a `Cu.import("resource://gre/modules/Services.jsm");` ) gives us a way to differentiate within Firefox but I'm not sure if that works in Thunderbird, nor if the name is as good a differentiator as the current GUID approach.

**Comment by luckyrat** [comment]
I think the approach I've just committed should still work with Thunderbird but I haven't had a chance to test it yet. It uses an XPCOM approach that predates the introduction of FUEL so hopefully we'll be good until Firefox removes XPCOM so probably at least a few years, at least for this aspect of cross-application compatibility.

ETA for the next beta is Wednesday so I'll be doing some more involved tests on that evening. @dlech if you have a chance to try out the latest version on master in Thunderbird before then that would be great.

**Comment by luckyrat** [comment]
New release that contains this fix: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/?page=1#version-1.6.0b3

**Comment by dlech** [comment]
Thunderbird commonDialog stuff is still working in 1.6.0b3.

**Comment by skibbipl** [comment]
In latest nightly authentication popup is changed again and KeeFox don't detect it anymore.

**Comment by Larusek** [comment]
Yes, I can confirm. Could you re-open this issue?

**Comment by dlech** [comment]
This is probably a different underlying problem this time. I would suggest opening a new issue.
